image: node:9.10

cache:
  paths:
  - node_modules/

tests:
  script:
  - npm install
  - npm run test

pages:
  script:
  - npm install
  - npm run build
  - rm -r public
  - mv dist public

  artifacts:
    paths:
    - public

  only:
    - master