image: node:9.10

cache:
  paths:
  - node_modules/

tests:
  script:
  - npm install
  - npm run test

pages:
  script:
  - npm install
  - npm run build
  - rm -r public
  - mv dist public
  # Hack to allow all routes to be picked up by front end router
  - cp public/index.html public/404.html

  artifacts:
    paths:
    - public

  only:
    - master