export default {
  INIT_COMPLETE: "INIT_COMPLETE",
  
  LOGOUT: "LOGOUT",
  LOGIN_BEGIN: "LOGIN_BEGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  SET_DATES: "SET_DATES",
  
  CLEAR_DATA: "CLEAR_DATA",
  EXERCISE_SOURCES_FETCH_BEGIN: "EXERCISE_SOURCES_FETCH_BEGIN",
  EXERCISE_SOURCES_FETCH_SUCCESS: "EXERCISE_SOURCES_FETCH_SUCCESS",
  EXERCISE_SOURCES_FETCH_FAILURE: "EXERCISE_SOURCES_FETCH_FAILURE",

  EXERCISE_SESSIONS_FETCH_BEGIN: "EXERCISE_SESSIONS_FETCH_BEGIN",
  EXERCISE_SESSIONS_FETCH_SUCCESS: "EXERCISE_SESSIONS_FETCH_SUCCESS",
  EXERCISE_SESSIONS_FETCH_FAILURE: "EXERCISE_SESSIONS_FETCH_FAILURE",

  EXERCISE_SETS_FETCH_BEGIN: "EXERCISE_SETS_FETCH_BEGIN",
  EXERCISE_SETS_FETCH_SUCCESS: "EXERCISE_SETS_FETCH_SUCCESS",
  EXERCISE_SETS_FETCH_FAILURE: "EXERCISE_SETS_FETCH_FAILURE",

  SET_1_REP_MAX: "SET_1_REP_MAX"
}